(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'json' is not defined"
p3
sS'layer'
p4
S'/home/pi/web2py/applications/planer/controllers/display.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# try something like\ndef index(): return dict(message="hello from display.py")\n\ndef weather():\n  import urllib2\n  url = "http://wttr.in/Krakow?format=j1"\n  opener = urllib2.build_opener()\n  opener.addheaders = [(\'Accept-Language\', \'pl\')]\n  content = opener.open(url)\n  c = json.loads(content)\n  display_weather()\n  return dict()\nresponse._vars=response._caller(weather)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/pi/web2py/applications/planer/controllers/display.py", line 14, in <module>\n  File "/usr/lib/python2.7/dist-packages/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/pi/web2py/applications/planer/controllers/display.py", line 11, in weather\n    c = json.loads(content)\nNameError: global name \'json\' is not defined\n'
p11
s.