(dp1
S'output'
p2
S"<type 'exceptions.IOError'> [Errno 2] No such file or directory: 'Krakow.json'"
p3
sS'layer'
p4
S'/home/pi/web2py/applications/planer/controllers/display.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n# try something like\ndef index(): return dict(message="hello from display.py")\n\ndef weather():\n  wszystko()\n  return dict()\nresponse._vars=response._caller(weather)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/pi/web2py/applications/planer/controllers/display.py", line 8, in <module>\n  File "/usr/lib/python2.7/dist-packages/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/pi/web2py/applications/planer/controllers/display.py", line 6, in weather\n    wszystko()\n  File "/home/pi/web2py/applications/planer/eink/bin/weather.py", line 29, in wszystko\n    with open("Krakow.json") as file:\nIOError: [Errno 2] No such file or directory: \'Krakow.json\'\n'
p11
s.